// How long a pointer-activated button ignores the click that follows it. The
// click normally arrives when the pointer lifts, so this only has to outlast a
// slow tap or a long press. If the click never arrives (the pointer slid off
// the button or was cancelled), the suppression expires so a later keyboard or
// assistive-technology click still works.
export const POINTER_CLICK_SUPPRESSION_MS = 1000;

interface ActivationTimers {
	setTimeout(handler: () => void, timeout: number): number;
	clearTimeout(handle: number): void;
}

/**
 * Whether a click came from a pointer press rather than the keyboard or
 * assistive technology. Chromium (Obsidian desktop and Android) reports clicks
 * as PointerEvents whose `pointerType` is "mouse", "touch" or "pen", and ""
 * for keyboard activation; its touch-tap clicks have `detail === 0`, so
 * `detail` alone cannot tell them apart. WebKit reports taps with
 * `detail >= 1` and keyboard clicks with `detail === 0`.
 */
function isPointerGeneratedClick(event: MouseEvent): boolean {
	const pointerType = (event as Partial<PointerEvent>).pointerType;
	if (typeof pointerType === "string" && pointerType !== "") {
		return true;
	}
	return event.detail > 0;
}

/**
 * Runs `onActivate` exactly once per press.
 *
 * Pointer input activates on `pointerdown` so pen and touch taps respond
 * immediately, and the `click` generated by that same press is then ignored.
 * Clicks without a preceding pointerdown (keyboard Enter/Space, assistive
 * technology) activate normally.
 */
export function bindSingleButtonActivation(
	button: HTMLButtonElement,
	timers: ActivationTimers,
	onActivate: () => void
): void {
	let suppressFollowingClick = false;
	let suppressionTimer: number | null = null;

	const clearSuppression = (): void => {
		suppressFollowingClick = false;
		if (suppressionTimer !== null) {
			timers.clearTimeout(suppressionTimer);
			suppressionTimer = null;
		}
	};

	button.addEventListener("pointerdown", (event) => {
		event.stopPropagation();
		if (button.disabled) {
			return;
		}
		if (event.pointerType === "mouse" && event.button !== 0) {
			return;
		}
		event.preventDefault();
		clearSuppression();
		suppressFollowingClick = true;
		suppressionTimer = timers.setTimeout(clearSuppression, POINTER_CLICK_SUPPRESSION_MS);
		onActivate();
	});

	button.addEventListener("click", (event) => {
		event.stopPropagation();
		event.preventDefault();
		if (suppressFollowingClick && isPointerGeneratedClick(event)) {
			clearSuppression();
			return;
		}
		clearSuppression();
		if (!button.disabled) {
			onActivate();
		}
	});
}
